extends:
  - '@commitlint/config-conventional'

rules:
  # Disable subject-case. We want to prefix with COMFY-xxxx
  subject-case:
    - 0
  type-enum:
    - 2
    - always
    - - build
      - chore
      - ci
      - docs
      - feat
      - fix
      - perf
      - refactor
      - revert
      - style
      - test
